ifneq ($(filter m y,$(CONFIG_USE_MMI_CHARGER)),)
	EXTRA_CFLAGS += -DUSE_MMI_CHARGER
	EXTRA_CFLAGS += -I$(src)/../mmi_charger
endif

ifneq ($(filter m y, $(ADAPTIVE_TOLERANCE_OPTIMIZATION)),)
	ccflags-y += -DADAPTIVE_TOLERANCE_OPTIMIZATION
endif

obj-$(CONFIG_QPNP_ADAPTIVE_CHARGE) += qpnp_adaptive_charge.o
