ccflags-$(CONFIG_DYNAMIC_UPDATE_UI_FULL) += -DDYNAMIC_UPDATE_UI_FULL

ifneq ($(filter m y,$(CONFIG_DYNAMIC_UPDATE_UI_FULL)),)
	EXTRA_CFLAGS += -DDYNAMIC_UPDATE_UI_FULL
endif

cw2217b_fg_mmi-objs += cw2217B_fuel_gauge_base.o
obj-$(CONFIG_CW2217B_FG_MMI) += cw2217b_fg_mmi.o
